Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -77,9 +77,9 @@ jobs:
   
     - name: Commit refreshed environment branch
       run: |
-        git add -A 
-        git commit -m "Updating ${{ github.event.inputs.instance }} with latest commits"
-        git push --set-upstream origin ${{ github.event.inputs.instance }} --force
+        git add -A || echo "ignore commit failure, proceed"
+        git commit -m "Updating ${{ github.event.inputs.instance }} with latest commits" || echo "ignore commit failure, proceed"
+        git push --set-upstream origin ${{ github.event.inputs.instance }} --force || echo "ignore commit failure, proceed"
   
     - name: Deploy looker code to instance
       run: |
